#!/usr/bin/env python
import os
import sys

from socket import gethostname

host_name = gethostname()

if host_name == 'service0' or host_name == 'service1':
  print 'Testing not supported on Icestorm head node'
  sys.exit(0)

sys.path += (os.path.dirname(os.path.abspath(__file__)) + '/tests')

#This junk is for running the tests with Bitten
test_dir='tests'
test_workdir_pos = 0
try:
  test_workdir_pos = sys.argv.index('TEST_WORKDIR')
  test_dir=os.path.join(sys.argv[test_workdir_pos+1],test_dir)
  sys.argv.pop(test_workdir_pos+1)
  test_workdir_pos = sys.argv.remove('TEST_WORKDIR')
except:
  pass

import nose
result = nose.run(argv=['./run_tests','-v','-w',test_dir]+sys.argv[1:])

# Was it completely successful?
if result:
  sys.exit(0)

sys.exit(1)
