#!/usr/bin/env python
import sys, os 

# Set the current working directory to the directory where this script is located
x=os.getcwd()
y=os.path.join(x,'scripts')

sys.path.append(y)

import creategrid